language: php

php:
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

addons:
    code_climate:
        repo_token: 9809d47c1966763efba0e4b167d2708267e9c767d953ce9e71918032c381d72c

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install:
  - composer install --no-interaction

script:
  - phpunit --bootstrap vendor/autoload.php --coverage-clover build/logs/clover.xml tests/

after_script:
  - vendor/bin/test-reporter